version: '3.9'

services:
  usercontrol.api:
    build:
      context: .
      dockerfile: UserControl/Dockerfile
    depends_on:
      - usercontrol.db
      - rabbitmq               
    environment:
      - ConnectionStrings__DefaultConnection=Server=usercontrol.db;Database=UserDatabase;User Id=sa;Password=Itgenius2025;TrustServerCertificate=True;
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Port=5672
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
    ports:
      - "5001:8080"

  usercontrol.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Itgenius2025"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    volumes:
      - usercontrol_data:/var/opt/mssql

  productcontrol.api:
    build:
      context: .
      dockerfile: ProductControl/Dockerfile
    depends_on:
      - productcontrol.db
      - rabbitmq                
    environment:
      - ConnectionStrings__DefaultConnection=Server=productcontrol.db;Database=ProductDatabase;User Id=sa;Password=Itgenius2025;TrustServerCertificate=True;
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Port=5672
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
    ports:
      - "5002:8080"

  productcontrol.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Itgenius2025"
      ACCEPT_EULA: "Y"
    ports:
      - "1436:1433"
    volumes:
      - productcontrol_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  usercontrol_data:
  productcontrol_data: